version: "3.9"
services:
  app:
    build: .
    container_name: warehouse-labeler
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/warehouse
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/backend/node_modules
      - /usr/src/app/frontend/node_modules
    working_dir: /usr/src/app
    command: npm run dev

  db:
    image: postgres:15
    container_name: warehouse-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: